// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoneActionServer.DAL;

#nullable disable

namespace StoneActionServer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723210206_trade")]
    partial class trade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("120a3330-bee5-409d-97d3-a151d4660b5c"),
                            Name = "Iron"
                        });
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.SlotInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.TradeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeSlots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28bf74df-6a4a-4a24-8f04-11329d1adcf6"),
                            Email = "email@",
                            PasswordHash = "dsf3sdf",
                            UserName = "Oc"
                        });
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.User", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("StoneActionServer.DAL.Models.Inventory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.SlotInventory", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.Inventory", "Inventory")
                        .WithMany("Slots")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneActionServer.DAL.Models.Item", "Item")
                        .WithMany("Slots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.TradeSlot", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.Item", "Item")
                        .WithMany("TradeSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneActionServer.DAL.Models.User", "User")
                        .WithMany("TradeSlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Item", b =>
                {
                    b.Navigation("Slots");

                    b.Navigation("TradeSlots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.User", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("TradeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
