// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoneActionServer.DAL;

#nullable disable

namespace StoneActionServer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423153905_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoneActionServer.DAL.Models.CraftingIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CraftingRecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("crafting_recipe_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_crafting_ingredient");

                    b.HasIndex("CraftingRecipeId")
                        .HasDatabaseName("ix_crafting_ingredient_crafting_recipe_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_crafting_ingredient_item_id");

                    b.ToTable("crafting_ingredient", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.CraftingRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ChanceOfSuccess")
                        .HasColumnType("double precision")
                        .HasColumnName("chance_of_success");

                    b.Property<int>("CraftingTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("crafting_time_seconds");

                    b.Property<int>("CraftingType")
                        .HasColumnType("integer")
                        .HasColumnName("crafting_type");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("integer")
                        .HasColumnName("result_item_id");

                    b.Property<int>("ResultQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_quantity");

                    b.HasKey("Id")
                        .HasName("pk_crafting_recipe");

                    b.ToTable("crafting_recipe", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventories_user_id");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.SlotInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_slots");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_slots_inventory_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_slots_item_id");

                    b.ToTable("slots", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.TradeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trade_slots");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_trade_slots_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trade_slots_user_id");

                    b.ToTable("trade_slots", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.CraftingIngredient", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.CraftingRecipe", "CraftingRecipe")
                        .WithMany("RequiredItems")
                        .HasForeignKey("CraftingRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_ingredient_crafting_recipe_crafting_recipe_id");

                    b.HasOne("StoneActionServer.DAL.Models.Item", "Item")
                        .WithMany("CraftingIngredient")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_ingredient_items_item_id");

                    b.Navigation("CraftingRecipe");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.User", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("StoneActionServer.DAL.Models.Inventory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.SlotInventory", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.Inventory", "Inventory")
                        .WithMany("Slots")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_inventories_inventory_id");

                    b.HasOne("StoneActionServer.DAL.Models.Item", "Item")
                        .WithMany("Slots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_items_item_id");

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.TradeSlot", b =>
                {
                    b.HasOne("StoneActionServer.DAL.Models.Item", "Item")
                        .WithMany("TradeSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_slots_items_item_id");

                    b.HasOne("StoneActionServer.DAL.Models.User", "User")
                        .WithMany("TradeSlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_slots_users_user_id");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.CraftingRecipe", b =>
                {
                    b.Navigation("RequiredItems");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Inventory", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.Item", b =>
                {
                    b.Navigation("CraftingIngredient");

                    b.Navigation("Slots");

                    b.Navigation("TradeSlots");
                });

            modelBuilder.Entity("StoneActionServer.DAL.Models.User", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("TradeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
